### ISSUE TITLE
消费队列时异常

### ISSUE THREAD

**Issue by 327** [freyo/laravel-queue-cmq#10]
当从队列获取数据时，发生如下报错信息：
 Unresolvable dependency resolving [Parameter #0 [ <required> $host ]] in class Freyo\LaravelQueueCMQ\Queue\Driver\Account

背景：
发生这种错误是通过这种方式创建的 job：

`
dispatch((new AttendanceJob($user->uid, $date))->onConnection('cmq')->onQueue('attendance'));
`

如果是自己通过 CMQ 的 Http API 创建的 job, 不会遇到这种情况

**Comment by freyo** [comment]
无法定位，麻烦贴下堆栈
