### ISSUE TITLE
能否麻烦写一下关于发布消息，消费消息的小demo，没有研究明白该如何使用

### ISSUE THREAD

**Issue by chaishubin** [freyo/laravel-queue-cmq#16]
如何新建一个队列，发布消息

**Comment by freyo** [comment]
1. 在 [腾讯云控制台 - 消息服务CMQ](https://console.cloud.tencent.com/mq/index) 创建队列
2. 参考 [README - configure](https://github.com/freyo/laravel-queue-cmq#configure) 配置参数
3. 参考 [Laravel - 队列](http://laravel.com/docs/queues#class-structure) 编写队列任务 Job
4. 参考 [README - dispatch-jobs](https://github.com/freyo/laravel-queue-cmq#dispatch-jobs) 发布消息
5. 参考 [README - process-jobs](https://github.com/freyo/laravel-queue-cmq#process-jobs) 监听队列消费消息

**Comment by chaishubin** [comment]
感谢回答，可能是我对laravel的job还不太熟悉，我自己在研究一下，感谢

**Comment by aweiht** [comment]
发布消息的demo没有啊

**Comment by freyo** [comment]
> 发布消息的demo没有啊

发布消息就是执行 [Dispatching Jobs](https://laravel.com/docs/6.x/queues#dispatching-jobs)

**Comment by aweiht** [comment]
执行 Dispatching Jobs的时候job里面的是如何去执行的，想问的是job里面的demo，比如我新建一个SendCMQ的job，我执行SendCmq::dispatch($data)的时候，这个sendCMQ里面如何去做呢？

**Comment by aweiht** [comment]
比如我要往cmq的topic里面扔一个消息，那么这个job里面的内容怎么去写？我想要的是这种demo

**Comment by freyo** [comment]
```php
<?php

namespace App\Jobs;

use Illuminate\Bus\Queueable;
use Illuminate\Contracts\Queue\ShouldQueue;
use Illuminate\Foundation\Bus\Dispatchable;
use Illuminate\Queue\InteractsWithQueue;
use Illuminate\Queue\SerializesModels;

class ExampleJob implements ShouldQueue
{
    use Dispatchable, InteractsWithQueue, Queueable, SerializesModels;

    public $queue = 'your-topic-key-or-tag'; // Topic 的 RouteKey 或 MsgTag

    protected $customData; // 你的自定义内容

    /**
     * Create a new job instance.
     *
     * @param $customData
     * @return void
     */
    public function __construct($customData)
    {
        $this->customData = $customData;
    }

    /**
     * Execute the job.
     *
     * @return void
     */
    public function handle()
    {
        // 在这里写你的处理逻辑
    }
}
```

**Comment by aweiht** [comment]
所以handle里面还是要像官方demo里面那么一长串发消息？

**Comment by aweiht** [comment]
emmm...简单点，就是怎么优雅的调用publish接口，因为官方demo都是先需要连接，在发布，很烦的一个过程下了

**Comment by freyo** [comment]
> emmm...简单点，就是怎么优雅的调用publish接口，因为官方demo都是先需要连接，在发布，很烦的一个过程下了

```php
$topic = app('queue')->connection('cmq')->getTopic();
$topic->publish_message($message, $vTagList, $routingKey);
```
