### ISSUE TITLE
队列任务处理失败时无法记录到数据库

### ISSUE THREAD

**Issue by zhangzhanpei** [freyo/laravel-queue-cmq#18]
往 failed_jobs 表写记录时，connection 列为赋值为 null，导致插入失败。这个值来自 CMQJob 类的成员属性 $connectionName。

**Comment by freyo** [comment]
Laravel/Lumen 版本是？

**Comment by zhangzhanpei** [comment]
Laravel 5.8.8

**Comment by freyo** [comment]
问题已确认，将在下个版本修复。

**Comment by freyo** [comment]
[5.8.5](https://github.com/freyo/laravel-queue-cmq/releases/tag/5.8.5) 已发布
