### ISSUE TITLE
Class 'Freyo\LaravelQueueCMQ\Queue\Driver\Message' not found 

### ISSUE THREAD

**Issue by 327** [freyo/laravel-queue-cmq#19]
版本是 5.7.4.1 请问这是什么原因？
 Class 'Freyo\LaravelQueueCMQ\Queue\Driver\Message' not found in /data/wwwroot/test.linde.smartlink.aidong.ai/vendor/freyo/laravel-queue-cmq/src/Queue/Driver/Queue.php:259 Stack trace: #0 /data/wwwroot/test.linde.smartlink.aidong.ai/vendor/freyo/laravel-queue-cmq/src/Queue/CMQQueue.php(159): Freyo\LaravelQueueCMQ\Queue\Driver\Queue->receive_message('1') #1 /data/wwwroot/test.linde.smartlink.aidong.ai/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(241): Freyo\LaravelQueueCMQ\Queue\CMQQueue->pop(Object(Freyo\LaravelQueueCMQ\Queue\Driver\Queue)) #2 /data/wwwroot/test.linde.smartlink.aidong.ai/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(104): Illuminate\Queue\Worker->getNextJob(Object(Freyo\LaravelQueueCMQ\Queue\CMQQueue), 'test-mse') #3 /data/wwwroot/test.linde.smartlink.aidong.ai/vendor/laravel/framework/src/Illuminate/Queue/Console/WorkCommand.php(101): Illuminate\Queue\Worker->daemon('cmq', 'test-mse', Object(Illuminate\Queue\WorkerOptions)) #4 /data/wwwroot/test.linde.smartlink.aidong.ai/vendor/laravel/framework/src/Illuminate/Queue/Console/WorkCommand.php(85): Illuminate\Queue\Console\WorkCommand->runWorker('cmq', 'test-mse') #5 [internal function]: Illuminate\Queue\Console\WorkCommand->fire() #6 /data/wwwroot/test.linde.smartlink.aidong.ai/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(29): call_user_func_array(Array, Array) #7 /data/wwwroot/test.linde.smartlink.aidong.ai/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(87): Illuminate\Container\BoundMethod::Illuminate\Container\{closure}() #8 /data/wwwroot/test.linde.smartlink.aidong.ai/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(31): Illuminate\Container\BoundMethod::callBoundMethod(Object(Illuminate\Foundation\Application), Array, Object(Closure)) #9 /data/wwwroot/test.linde.smartlink.aidong.ai/vendor/laravel/framework/src/Illuminate/Container/Container.php(539): Illuminate\Container\BoundMethod::call(Object(Illuminate\Foundation\Application), Array, Array, NULL) #10 /data/wwwroot/test.linde.smartlink.aidong.ai/vendor/laravel/framework/src/Illuminate/Console/Command.php(182): Illuminate\Container\Container->call(Array) #11 /data/wwwroot/test.linde.smartlink.aidong.ai/vendor/symfony/console/Command/Command.php(255): Illuminate\Console\Command->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Illuminate\Console\OutputStyle)) #12 /data/wwwroot/test.linde.smartlink.aidong.ai/vendor/laravel/framework/src/Illuminate/Console/Command.php(167): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Illuminate\Console\OutputStyle)) #13 /data/wwwroot/test.linde.smartlink.aidong.ai/vendor/symfony/console/Application.php(969): Illuminate\Console\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput)) #14 /data/wwwroot/test.linde.smartlink.aidong.ai/vendor/symfony/console/Application.php(255): Symfony\Component\Console\Application->doRunCommand(Object(Illuminate\Queue\Console\WorkCommand), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput)) #15 /data/wwwroot/test.linde.smartlink.aidong.ai/vendor/symfony/console/Application.php(148): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput)) #16 /data/wwwroot/test.linde.smartlink.aidong.ai/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(122): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput)) #17 /data/wwwroot/test.linde.smartlink.aidong.ai/artisan(35): Illuminate\Foundation\Console\Kernel->handle(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput)) #18 {main} [] []

**Comment by freyo** [comment]
先尝试执行 `composer dump`  或 更新最新版本 是否解决。另外请提供一下 **运行环境** 和 **Laravel/Lumen 版本**。
