### ISSUE TITLE
Nonce 重复导致请求失败

### ISSUE THREAD

**Issue by 327** [freyo/laravel-queue-cmq#21]
之前跟腾讯云确认过，他们 PHP SDK 有个 bug，当 Nonce 值相同时，CMQ Server 会认为是重复请求。所以调整 Nonce 的生成规则，防止在大并发请求下，Nonce 值重复

![image](https://user-images.githubusercontent.com/2648290/64606112-1047c580-d3f8-11e9-9203-59d7e83a22c2.png)

**Comment by 327** [comment]
可以采纳吗？

**Comment by 327** [comment]
是否设置了不允许提交 PR？

**Comment by freyo** [comment]
可以。你提交一下 [PR](https://github.com/freyo/laravel-queue-cmq/compare/master...327:master)

**Comment by freyo** [comment]
[5.8.6](https://github.com/freyo/laravel-queue-cmq/releases/tag/5.8.6) released
