### ISSUE TITLE
Pop the next job off of the queue.

### ISSUE THREAD

**Issue by kylin1wang2** [freyo/laravel-queue-cmq#7]
`/**
     * Pop the next job off of the queue.
     *
     * @param  string $queue
     *
     * @return \Illuminate\Contracts\Queue\Job|null
     */
    public function pop($queue = null)
    {
        try {
            $queue   = $this->getQueue($queue);
            $message = $queue->receive_message($this->queueOptions['polling_wait_seconds']);
        } catch (CMQServerException $e) {
            if ($e->getCode() == self::CMQ_QUEUE_NO_MESSAGE_CODE) { //ignore no message
                return null;
            }
            throw $e;
        }

        return new CMQJob($this->container, $this, $message, $queue);
    }`

请问这个$this->container应该传什么值

**Comment by freyo** [comment]
The IoC container instance, `instanceof \Illuminate\Container\Container`, just pass `app()` or `\Illuminate\Container\Container::getInstance()`
